apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"myapp"},"name":"php-app","namespace":"php-project"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"myapp"}},"template":{"metadata":{"labels":{"app":"myapp"}},"spec":{"containers":[{"image":"quay.io/anwarfouad/php-app","name":"myapp-php","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2024-04-22T22:43:58Z"
  generation: 1
  labels:
    app: myapp
  name: php-app
  namespace: php-project
  resourceVersion: "85932"
  uid: 21e73d5d-a169-4c52-a6e2-95bb777289d1
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
    spec:
      containers:
      - image: quay.io/anwarfouad/php-app
        imagePullPolicy: Always
        name: myapp-php
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-04-22T22:44:11Z"
    lastUpdateTime: "2024-04-22T22:44:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-22T22:43:58Z"
    lastUpdateTime: "2024-04-22T22:44:11Z"
    message: ReplicaSet "php-app-5496766d77" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
